// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx8-VZcRbKfw2hDUhYf2rPLBj8uXUuJYA',
    appId: '1:254807950570:android:1ff28898b5edf0bf98c393',
    messagingSenderId: '254807950570',
    projectId: 'tripmate-flutter-86218',
    storageBucket: 'tripmate-flutter-86218.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7eyt3iNteWD0kR5UZhkXcrknb3mp5M9k',
    appId: '1:254807950570:web:b029589e2a3f137598c393',
    messagingSenderId: '254807950570',
    projectId: 'tripmate-flutter-86218',
    authDomain: 'tripmate-flutter-86218.firebaseapp.com',
    storageBucket: 'tripmate-flutter-86218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQu8n7NaITUboCZlGdFUiLBk_WS9fSdCk',
    appId: '1:254807950570:ios:45a3d6e03f61f93598c393',
    messagingSenderId: '254807950570',
    projectId: 'tripmate-flutter-86218',
    storageBucket: 'tripmate-flutter-86218.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTripmate',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQu8n7NaITUboCZlGdFUiLBk_WS9fSdCk',
    appId: '1:254807950570:ios:45a3d6e03f61f93598c393',
    messagingSenderId: '254807950570',
    projectId: 'tripmate-flutter-86218',
    storageBucket: 'tripmate-flutter-86218.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTripmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7eyt3iNteWD0kR5UZhkXcrknb3mp5M9k',
    appId: '1:254807950570:web:75c59c9321b14b1698c393',
    messagingSenderId: '254807950570',
    projectId: 'tripmate-flutter-86218',
    authDomain: 'tripmate-flutter-86218.firebaseapp.com',
    storageBucket: 'tripmate-flutter-86218.firebasestorage.app',
  );
}
